name: wing_man
description: "Wing man is a dating helper APP"

publish_to: "none"

version: 1.0.0+1

environment:
    sdk: ">=3.7.2 <4.0.0"

dependencies:
    flutter:
        sdk: flutter
    http: ^1.1.0
    cupertino_icons: ^1.0.8
    flutter_native_splash: ^2.4.6
    fluttertoast: ^8.2.5
    flutter_svg: ^1.1.6

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^2.0.0
    flutter_launcher_icons: ^0.14.4

flutter_icons:
    android: "launcher_icon"
    ios: true
    image_path: "assets/logo/logo.png"
    min_sdk_android: 21
    web:
        generate: true
        image_path: "assets/logo/logo.png"
        background_color: "#FFFFFF"
        theme_color: "#000000"
    windows:
        generate: true
        image_path: "assets/logo/logo.png"
        icon_size: 48
    macos:
        generate: true
        image_path: "assets/logo/logo.png"

flutter:
    uses-material-design: true
    assets:
        - assets/images/splash_logo.png
        - assets/logo/logo.png

flutter_native_splash:
    color: "#FFFFFF"
    image: assets/images/splash_logo.png

    android_12:
        image: assets/images/splash_logo.png
        color: "#FFFFFF"
