name: wing_man
description: "Wing man is a dating helper APP"

publish_to: "none"

version: 1.0.0+1

environment:
    sdk: ">=3.7.2 <4.0.0"

dependencies:
    flutter:
        sdk: flutter
    http: ^1.1.0
    cupertino_icons: ^1.0.8
    flutter_native_splash: ^2.4.6
    fluttertoast: ^8.2.5
    flutter_svg: ^1.1.6

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^2.0.0

flutter:
    uses-material-design: true

    # Make sure this asset path is correct
    assets:
        - assets/images/splash_logo.png

# Add this block at the same level as the 'flutter:' block
flutter_native_splash:
    # The color you want for the background
    color: "#FFFFFF"

    # The image you want to use
    image: assets/images/splash_logo.png

    # For Android 12 and newer, a separate configuration is often needed
    android_12:
        image: assets/images/splash_logo.png
        color: "#FFFFFF"
